name: PYTHON CI

# Triger the workflow whenever there is a push request to the main or pull request queue
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the git repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Generate coverage report
        run: |
          python -m unittest discover tests

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
